YoussSrt/sloop

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/policies/application_policy.rb
mise en place de pundit
bundle install
rails generate pundit:install
et configuration de ApplicationController
=> installation de pundit

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/pages/home.html.erb, app/views/pages/profile.html.erb, config/environments/development.rb, config/routes.rb
added profile method in pages controller
created homepage
created profile page
added pundit in application controller
=> controllers + home page + profile page

app/views/pages/home.html.erb, app/views/pages/profile.html.erb
revue de la home page
ajout du texte de presentation
revue de if user logged in ou pas
ajout de bouton New sloop
=> homepage adjustment

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_layout.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
=> footer sticky

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_fonts.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
ajout de la navbar,
strcuture des boutons
ajout des liens de renvoi
=> navbar structure done

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_chat.scss, app/assets/stylesheets/components/_index.scss, app/channels/application_cable/channel.rb, app/channels/application_cable/connection.rb, app/controllers/application_controller.rb, app/controllers/chatrooms_controller.rb, app/controllers/messages_controller.rb, app/javascript/controllers/chat_controller.js, app/javascript/controllers/reset_form_controller.js, app/javascript/controllers/scroll_controller.js, app/models/chatroom.rb, app/models/concerns/current.rb, app/models/message.rb, app/views/chatrooms/create.html.erb, app/views/chatrooms/index.html.erb, app/views/chatrooms/show.html.erb, app/views/messages/_form.html.erb, app/views/messages/_message.html.erb, app/views/messages/create.html.erb, config/environments/development.rb, config/routes.rb, test/controllers/chatrooms_controller_test.rb, test/controllers/messages_controller_test.rb
ajout de la messagerie
controller stimulus
ajout de Turbo stream
ajout du CSS
ajout de la partial message
=> messagerie done

app/assets/stylesheets/components/_chat.scss, app/controllers/chatrooms_controller.rb, app/javascript/controllers/message_form_controller.js, app/views/chatrooms/show.html.erb, app/views/shared/_sidebar.html.erb, config/routes.rb
ajout de la side bar avec les users dispos
=> messagerie revue avec side bar

app/controllers/application_controller.rb, app/controllers/sloopies_controller.rb, app/services/open_ai_service.rb, app/views/sloopies/index.html.erb, app/views/sloopies/show.html.erb, db/migrate/20241127154514_add_details_to_steps.rb, db/migrate/20241127154953_rename_city_name_to_city_and_remove_step_duration.rb, db/migrate/20241127155143_add_address_to_activities.rb, db/migrate/20241127155250_add_summary_to_sloopies.rb, db/schema.rb, db/seeds.rb
Service openai (prompt, parse de la reponse en JSON, recuperation des informations cout, city, activities, etc...)
Modifications des tables pour concordances avec les données récupérées 
Creation des sloopies via chatgpt ok !!
=> service openai done, creation de sloopies via chatgpt ok

app/assets/stylesheets/application.scss, db/schema.rb
=> version 1 maps

Gemfile, Gemfile.lock
ajout de Mapbox key
ajout de Gem geocoder
Bundle install
=> maps ajout key

app/assets/stylesheets/components/_sloopy-index.scss, app/assets/stylesheets/config/_fonts.scss, app/controllers/sloopies_controller.rb, app/views/sloopies/index.html.erb
=> front index sloopies

app/controllers/sloopies_controller.rb
=> maps markers done

app/controllers/sloopies_controller.rb, app/views/sloopies/index.html.erb
maps marker fait une bonne fois pour toute
=> maps marker fuckin done

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_preferences.scss, app/helpers/application_helper.rb, app/javascript/controllers/next_button_controller.js, app/javascript/controllers/preferences_form_controller.js, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_preferences.html.erb
front formulaire interests
orange button
controller next_button
=> formulaire

app/controllers/sloopies_controller.rb, app/javascript/controllers/map_controller.js, config/routes.rb
map revue avec globe
mise en place des markers
=> Finalchatroom

app/javascript/controllers/next_button_controller.js, app/javascript/controllers/preferences_form_controller.js, app/views/shared/_preferences.html.erb
=> functionnal

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_sloopy-index.scss, app/controllers/pages_controller.rb, app/services/open_ai_service.rb, app/views/pages/home.html.erb, app/views/sloopies/_form.html.erb, app/views/sloopies/show.html.erb, db/migrate/20241129112403_add_stays_to_steps.rb, db/schema.rb
=> form sur la home done

app/assets/stylesheets/components/_map.scss, app/controllers/sloopies_controller.rb, app/javascript/controllers/map_controller.js, app/views/sloopies/index.html.erb, app/views/sloopies/show.html.erb
ajout de la map globe
show done
index done
=> index et show done + maps faite

app/assets/stylesheets/pages/_index.scss, app/views/sloopies/show.html.erb, db/schema.rb
ajout de stays night sur la show
=> ajout de stays dans show

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_index.scss
=> update CSS components and pages

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_profile.scss, app/assets/stylesheets/profile.css, app/views/pages/profile.html.erb, app/views/shared/_navbar.html.erb
ajout de la profile page
revue du background
=> ajout de la profile page et revue du background

app/assets/stylesheets/components/_map.scss, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/sloopies/show.html.erb
=> ajout de la sticky map

Gemfile, Gemfile.lock, app/controllers/sloopies_controller.rb, app/jobs/generate_sloopy_job.rb, app/models/sloopy.rb, app/services/open_ai_service.rb, app/views/sloopies/_map.html.erb, app/views/sloopies/_sloopy.html.erb, app/views/sloopies/index.html.erb, bin/jobs, config/application.rb, config/cable.yml, config/environments/production.rb, config/initializers/active_job.rb, config/puma.rb, config/queue.yml, config/recurring.yml, db/migrate/20241202140601_install_solid_queue.rb, db/migrate/20241202151900_create_solid_cable_message.solid_cable.rb, db/migrate/20241202151901_index_channels.solid_cable.rb, db/queue_schema.rb, db/schema.rb
ajout du fuckin background job avec le chargement de la page!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=> ajout du background jobs

app/assets/stylesheets/components/_sloopy-index.scss, app/services/open_ai_service.rb, app/views/sloopies/index.html.erb, app/views/sloopies/show.html.erb, app/views/sloopies/steps/_sloop_details.html.erb, db/migrate/20241202094914_add_budget_estimated_to_sloopy.rb, db/migrate/20241202155122_change_budget_estimated_to_string_in_sloopies.rb, db/schema.rb
modif du prompt pour generer 2 sloopies
plus ajout des infos sur la show/ budget sur l'index
=> modif du prompt pour generer 2 sloopies

app/controllers/sloopies_controller.rb, app/javascript/application.js, app/views/sloopies/_status_button.html.erb, app/views/sloopies/show.html.erb, config/routes.rb
=> done or not

app/controllers/application_controller.rb, app/controllers/users/registrations_controller.rb, config/routes.rb
after sign up path vers preferences
=> preferences after sign up

= {, app/controllers/steps_controller.rb, app/javascript/controllers/reset_form_controller.js, app/jobs/chatbot_job.rb, app/models/activity.rb, app/models/sloopy.rb, app/models/step.rb, app/services/open_ai_service.rb, app/views/questions/_form.html.erb, app/views/sloopies/show.html.erb, config/routes.rb, test/controllers/steps_controller_test.rb
ajout du chatbot dans la show, possibilité de communiquer avec lui et methode pour update les steps almost done (à finir demain)!!!
=> ajout chatbot + methode pour modif les steps almost done

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_chatrooms.scss, app/views/pages/profile.html.erb, config/routes.rb
revue de la messagerie avec meilleur style
=> messagerie style revue

app/assets/stylesheets/pages/_profile.scss, app/views/pages/profile.html.erb
=> profile page revu

app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_sloopy-index.scss, app/assets/stylesheets/pages/_profile.scss, app/views/pages/profile.html.erb, app/views/sloopies/index.html.erb
revue de la chatroom et de la profile
=> revue de la profile

app/assets/stylesheets/pages/_chatrooms.scss, app/controllers/chatrooms_controller.rb, app/models/message.rb, app/models/user.rb, app/views/chatrooms/show.html.erb, app/views/shared/_sidebar.html.erb, app/views/sloopies/_save_button.html.erb, app/views/sloopies/_sloopy.html.erb, app/views/sloopies/show.html.erb
surbrillance des messages,
chargement auto avec turbo stream
dernier message tout en haut de la liste en instantané
=> revue de toute la messagerie

app/controllers/pages_controller.rb, app/controllers/users_controller.rb, app/views/pages/feed.html.erb, app/views/pages/other_user_profile.html.erb, config/routes.rb, db/schema.rb
=> other_profil_page

app/assets/stylesheets/pages/_profile.scss, app/controllers/sloopies_controller.rb, app/javascript/controllers/map_controller.js, app/views/pages/profile.html.erb, app/views/sloopies/_profile_card.html.erb, app/views/sloopies/_sloopy.html.erb, app/views/sloopies/show.html.erb
revue de l'index, 
revue de la card + button save
=> revue de l'index avec save et cards

app/assets/stylesheets/pages/_feed.scss, app/controllers/sloopies_controller.rb
=> copy update

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_sloopy-index.scss, app/assets/stylesheets/pages/_feed.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_new_sloopie.scss, app/controllers/sloopies_controller.rb, app/views/layouts/application.html.erb, app/views/pages/feed.html.erb, app/views/shared/_footer.html.erb, app/views/sloopies/show.html.erb
=> copy et marge

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_profile.scss, app/assets/stylesheets/pages/_sloopies_index.scss, app/controllers/sloopies_controller.rb, app/javascript/controllers/map_controller.js, app/views/pages/profile.html.erb, app/views/sloopies/_loading_card.html.erb, app/views/sloopies/_map.html.erb, app/views/sloopies/_realized_card.html.erb, app/views/sloopies/_sloopy.html.erb, app/views/sloopies/index.html.erb, db/schema.rb
=> revue de l'index

app/assets/stylesheets/components/_loader.scss, app/assets/stylesheets/components/_loading-page.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_sloopy-index.scss, app/assets/stylesheets/pages/_new_sloopie.scss, app/assets/stylesheets/pages/_sloopies_index.scss, app/views/sloopies/index.html.erb
=> revue avant heroku

app/views/sloopies/index.html.erb, app/views/sloopies/steps/_sloop_details.html.erb
ajout du curseur qui swing
revue du title de l'index plus styleyyy
=> revue du title et du cursor

app/assets/stylesheets/pages/_profile.scss, db/schema.rb
=> bouton chatroom over everything

app/assets/stylesheets/pages/_feed.scss, app/views/pages/feed.html.erb
=> revue de tout le feed

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_sloopy-index.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/reviews/_review_form.html.erb, app/views/sloopies/show.html.erb, app/views/sloopies/steps/_sloop_details.html.erb, db/schema.rb
=> show, footer

app/assets/stylesheets/pages/_profile.scss, app/views/pages/other_user_profile.html.erb
=> chatroom enfin finiiiiiiiiiiiiiiiiiiie

app/controllers/sloopies_controller.rb
=> final fix pour la map

app/assets/stylesheets/pages/_profile.scss, app/controllers/reviews_controller.rb, app/controllers/sloopies_controller.rb, app/views/pages/profile.html.erb, app/views/reviews/_review.html.erb, app/views/reviews/_review_form.html.erb, app/views/reviews/edit.html.erb, app/views/reviews/new.html.erb, app/views/reviews/show.html.erb, db/migrate/20241205141538_change_column_type_status.rb, db/schema.rb
=> status db corrected

app/controllers/pages_controller.rb
=> redirect done

app/views/pages/about.html.erb, app/views/pages/profile.html.erb, app/views/sloopies/index.html.erb, app/views/sloopies/show.html.erb, app/views/sloopies/steps/_sloop_details.html.erb
revue de l'index
revue de la map
redirect to depuis profil
=> revue finale

app/assets/stylesheets/components/_avatar.scss, app/views/pages/other_user_profile.html.erb, app/views/shared/_sidebar.html.erb
=> last fixes
